### PR TITLE
UI improvements

### PR DESCRIPTION
**Pull request by equinusocio**
Toolbar improvements and minor buttons/search input fix.

screen shot 2015-10-12 at 20 38 52

### CODE REVIEW

**Comment by equinusocio** [comment]
I will update the README and others screenshots today.

**Comment by bengotow** [comment]
Hey Mattia,

Thanks for these contributions! Hold tight and I'll check with our team about the visual changes to the light theme. We may want to collect changes and take another pass at the theme in a few months, since we're in the middle of customizing the existing visual style for Linux and Windows, and there will be a full time designer helping coordinate improvements and keep things consistent soon.

In the meantime, if you have ideas or adjustments for the dark theme, we can land those more easily. It'd also be cool to create a variant of the light theme to take things in a new direction!

**Comment by equinusocio** [comment]
Yes, after this i will work on the darker version. I will wait for a theme chooser before make a new one :)

**Comment by bengotow** [comment]
We've decided to keep the standard Mac gradient in the toolbar for now, closing this. In the future when we have a package browser, it'd be great to publish this as a theme!

**Comment by equinusocio** [comment]
:+1:

**Comment by grinich** [comment]
@equinusocio how's that material theme coming? :)

**Comment by equinusocio** [comment]
At the moment i'm designing the UI. There is a lot of work to do :). I've created the repo with test files.

**Pull request closed without merging**
