### PR TITLE
Convert Atom's launch script for N1

### PR DESCRIPTION
**Pull request by mbilker**
Addresses #411

The `N1.sh` launch script fails to account for running from `/usr/bin/nylas` or `/usr/local/bin/nylas` or `/opt/N1/bin/nylas` where it would throw an error saying it couldn't find the electron binary.

The Atom launch script works just fine and takes that into account. The installed launch script here is a refactored Atom launch script that properly accounts for running the `nylas` executable and locates the actual binary accordingly.

### CODE REVIEW

**Comment by mbilker** [comment]
I did not incorporate the AppVeyor development branch into this PR.

**Comment by mbilker** [comment]
The current AppVeyor setup requires access to the project secrets in order to build.

**Comment by whitelynx** [comment]
Any chance this could be rebased and merged? It'd be nice if an installed version of N1 actually worked out of the box...

**Comment by mbilker** [comment]
@whitelynx N1 works out of the box. This PR just fixes the `/usr/bin/nylas` script. You can still launch N1 via `/usr/share/nylas/nylas`.

**Comment by mbilker** [comment]
@bengotow When can this be merged? Some people complained about this on Slack, but it is a low priority issue.

**Comment by bengotow** [comment]
Hey @mbilker — sorry for the delay on this one. We talked about this internally, and it'd be great if we could add the relevant Linux bits of `nylas.sh` (lines 89-116 I think?) to the existing `N1.sh` file in the root of the repository. I think there are a lot of things in that `nylas.sh` file pulled from `atom.sh` that we don't need anymore, and it might be confusing for the repo to have both N1.sh and nylas.sh.

I think we should also edit `install-task.coffee` to copy the file to both `N1.sh` and `nylas.sh` in the user's bin directory so that they can also do `N1` from the command line.

**Comment by mbilker** [comment]
I see what you are saying @bengotow. The current `N1.sh` in the root of the repository allows N1 to be run from source using the `electron` command, and my script does not take this into account.

I do notice some parts of this `nylas.sh` are not needed anymore as they pertain to only Atom's launch script. I do believe the output handling parts are essential so I don't have to type `ELECTRON_ENABLE_LOGGING=1` every time.

**Comment by mbilker** [comment]
Is there anything else I need to do to the script?

**Comment by emorikawa** [comment]
Hey @mbilker This looks great. Thank you! Sorry for the delay on this one. I just rebased this on top of master and pushed.

**Comment by mbilker** [comment]
Thanks @emorikawa !

**Pull request closed without merging**
