### PR TITLE
Travis build script rework to allow completion under Pull Requests

### PR DESCRIPTION
**Pull request by mbilker**
This PR stems from recent failures I encountered at [my forked repository](https://travis-ci.org/mbilker/N1) and with the PR's I sent here.

In nylas/N1@989f38ca77e56eaf3d8457b6c2ed03b14b5f6fcd the entire build script was merged from Evan Morikawa's branch for integrating AppVeyor, which reordered the whole Travis build script. This PR  reorders the to have the Travis build environment config at the beginning of the script and the build process at the end and the Travis secure variables at the end of the script.

I also added added some conditions to run the decryption commands only on the main repository using `TRAVIS_PULL_REQUEST` from [Testing Pull Requests](https://docs.travis-ci.com/user/pull-requests).

### CODE REVIEW

**Comment by bengotow** [comment]
Hey — thanks! cc @emorikawa

**Comment by emorikawa** [comment]
@mbilker this looks great. Thanks for re-ordering to be more sensible and making it work on non-mainline branches. I just pushed after a rebase.

**Comment by mbilker** [comment]
Shoot. `ssh-keyscan` on the OS X hosts is failing because it doesn't recognize ECDSA.

**Comment by mbilker** [comment]
Weird thing is. https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/addons/ssh_known_hosts.rb#L42-L47 says it only sets it to RSA and DSA on OS X.

**Pull request closed without merging**
