### PR TITLE
Fix a couple of typos and a syntax error

### PR DESCRIPTION
**Pull request by boffbowsh**

### CODE REVIEW

**Comment by dillonforrest** [comment]
Thanks much for the contribution @boffbowsh! :) Everybody here at Nylas really appreciates it!!

**Comment by dillonforrest** [comment]
Hey there @boffbowsh, super sorry to bother you about this, but can you also sign our CLA? https://nylas.com/cla

I know it's annoying (we're sorry!!), but our stakeholders require all our contributors to sign it. We made it similar to [Facebook's CLA](https://code.facebook.com/cla). It'd mean a lot to us if you could sign it! :)

**Comment by boffbowsh** [comment]
Just revert the PR if the CLA is that important. Sorry, but I'm not giving you those details. You might also want to make the CLA requirement clear in CONTRIBUTING.md

**Comment by dillonforrest** [comment]
Ah okay, thanks for the feedback @boffbowsh. If you don't mind me asking, what information was the form asking for which you didn't want to give?

Also, it's completely my mistake for not adding the CLA to CONTRIBUTING.md. I just added it a few minutes ago! Sorry about that. -__-

**Comment by grinich** [comment]
Hey @boffbowsh -- thanks again for this contribution, and sorry for the overzealous application of the CLA. :) We've been running the (Nylas Sync Engine)[https://github.com/nylas/sync-engine] as an open source project for several years, but this is the first time we have docs in the main repo!

**Pull request merged**
