### PR TITLE
use valid SPDX license code in package.json files

### PR DESCRIPTION
**Pull request by slang800**

### CODE REVIEW

**Comment by bengotow** [comment]
Ahh good catch—thanks for contributing this. I know it's a bit of a pain, but could you sign the open source CLA? (https://nylas.com/cla). That'll make the bot happy and I can land this. Welcome to the project!

**Comment by slang800** [comment]
lol, no... I'm not bearing any [legal risk](https://sfconservancy.org/blog/2014/jun/09/do-not-need-cla/) for something as trivial as having a patch merged.

**Comment by grinich** [comment]
Hi @slang800 -- do you have a specific issue with the way the CLA is structured? This agreement is essentially the same as the [Meteor CLA](https://contribute.meteor.com/) which is derived from the Apache Software Foundation’s Individual CLA.

**Comment by bengotow** [comment]
Doesn't seem this is going anywhere—closing this and switching license code formats on our side.

**Pull request closed without merging**
