### PR TITLE
Enables showing/hiding of menubar

### PR DESCRIPTION
**Pull request by AskBre**
Enables showing/hiding of the menubar as per feature request #1181

### CODE REVIEW

**Comment by bengotow** [comment]
Hey! Does this also work if you use the new setting name (`autoHideMenuBar` https://github.com/electron/electron/blob/master/docs/api/browser-window.md#new-browserwindowoptions)?

**Comment by AskBre** [comment]
Hey, I keep getting `ERROR:browser_main_loop.cc(219)] Running without the SUID sandbox!`, but will try it as soon as I get the time to fix it.

**Comment by AskBre** [comment]
It does indeed work with the new setting name too. Pushed a new commit.

**Comment by bengotow** [comment]
Cool! Gonna land this and we'll ship it in the release tomorrow.

**Pull request merged**
