### PR TITLE
Typo: mispelled > misspelled

### PR DESCRIPTION
**Pull request by agsdot**
http://grammar.yourdictionary.com/spelling-and-word-lists/misspelled.html

### CODE REVIEW

**Comment by grinich** [comment]
The irony of misspelling this is not lost on me.

**Comment by agsdot** [comment]
@grinich, I was thinking that too.  All good. Thanks for making a great product once again.

**Comment by grinich** [comment]
af9zefy

**Comment by agsdot** [comment]
Yup, just like the amazing gif, Nylas, an amazing product. 

So much better an experience from when I used to use Thunderbird many years back.  Seemless integration of both google apps and ms exchange.

**Pull request merged**
