### PR TITLE
Add basic travis-ci integration

### PR DESCRIPTION
**Pull request by sbstnmsch**
Adds travis-ci integration including setup, building and testing your specs. Though this is currently not succeeding on Node 4 this might be a good idea to run continuous integration tests on this fabulous peace of software.

### CODE REVIEW

**Comment by sbstnmsch** [comment]
Pushed dot 10 to my fork - waiting for travis to build and test.

**Comment by sbstnmsch** [comment]
Done it. Travis`ed it. Build ok. Please please don't ask me to squash those merge commits at 1am on Mondays in Berlin cause Berghain Club is waiting for me ;-)

**Comment by emorikawa** [comment]
This looks great! Thank you so much for getting this up.

**Comment by dillonforrest** [comment]
Hey there @sbstnmsch, thanks for this awesome PR! Can I trouble you to sign the Nylas CLA? https://nylas.com/cla

It's really important for all our stakeholders that all our contributors sign it. I know it's annoying, and I'm sorry about that! But it'd mean a lot to us if you could sign it. :)

(Btw, our CLA is very similar to the [Facebook CLA](https://code.facebook.com/cla))

**Comment by sbstnmsch** [comment]
Done. I really appreciate your work and like to help - cause i longed for this piece of software since 1993!

One more thing: Could you please invite/ unlock me again (sbstnmsch AAAAATTTTT gmail <mailto:sbstnmsch@gmail.com>) cause currently i’m locked out of Nylas :-(

Greetings from Berlin,
Sebastian Misch

**Comment by sbstnmsch** [comment]
Back in. Note to users locked out and having a fresh invitation code which cannot be entered into an existing (locked) Nylas install:

- quit it
- do `rm -rf ~/.nylas*`
- restart
- enter code and you are all in

**Pull request merged**
