### PR TITLE
[RFC] Linux 32-bit Docker build

### PR DESCRIPTION
**Pull request by mbilker**
In response to #254 and #139, I developed a Docker build for Linux that uses a 32-bit Docker image and builds N1. I used Atom's Fedora Docker buildfile as a template and went from there.

This PR adds the ability to use the Docker build, but needs complete testing for the `publish-nylas-build` task.

I was able to get the Docker to build the `deb` and `rpm` files like the regular CI build process does.

### CODE REVIEW

**Comment by mbilker** [comment]
I am having weird issues with `npm` and errors like:
```
Node: v4.3.0
npm: v2.14.12

---> Installing N1 build tools
     This goes inside the `build` folder and runs `npm install`
     It will use the system `npm` to bootstrap our own N1 npm.
     Our build tools (like Grunt) need to be compiled against Node via `npm`.
     Everything else needs to be compiled against Chromium with `apm`.

     $ npm --userconfig="/n1/.npmrc" install --loglevel error --cwd=/n1/build --ignoreStdout=true 

npm ERR! Linux 4.4.1-2-ARCH
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "--userconfig=/n1/.npmrc" "install" "--loglevel" "error"
npm ERR! node v4.3.0
npm ERR! npm  v2.14.12
npm ERR! path /root/.npm/registry.npmjs.org/async/.cache.json.e7e4f2eae65ea11ccc8212cc167788a3
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall lstat

npm ERR! enoent ENOENT: no such file or directory, lstat '/root/.npm/registry.npmjs.org/async/.cache.json.e7e4f2eae65ea11ccc8212cc167788a3'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /n1/build/npm-debug.log
```

**Comment by mbilker** [comment]
That error does not appear every Docker build.

**Comment by mbilker** [comment]
I got it to build everything! Now to get the `deb` out of the container.

**Comment by Revod** [comment]
Amazing @mbilker  thanks for you work :100:

**Comment by mbilker** [comment]
I would like some comments on the implementation of this into the unit testing.

**Comment by bengotow** [comment]
Hey! This looks good to me and we finally had a chance to test it a bit internally. We still need to double check that `publish-nylas-build` correctly uploads the builds to `i386` and `x64` folders correctly when run from the docker build, but I think it will so we've decided to test it on master. :-).

Thanks!

**Comment by mbilker** [comment]
Oh well thanks! This docker is only for `ia32` builds of Electron to satisfy the 32-bit audience.

**Pull request merged**
