### PR TITLE
Match only valid URLs for link tracking

### PR DESCRIPTION
**Pull request by ridem**
As of now, link-tracking creates link tracking for every <a> tag, no matter the href attribute. This commit only creates link tracking for valid URLs.
The reason I wrote a new regex instead of rewriting linkTagRegex is that this regex is used by message-list.
https://regex101.com/r/jD5zC7/3 vs https://regex101.com/r/cK0zD8/2

Resolves: #1525

### CODE REVIEW

**Comment by ridem** [comment]
I believe the travis-ci won't fail with commit #1520

**Comment by dregitsky** [comment]
Hey @ridem, thanks for writing this! That's a really good catch with `mailto:`, we definitely don't want to replace those with redirects.

It looks like the new regex won't match `href="google.com"` though, which actually is a valid class of URLs we'd want to replace. It'd be great if the regex could match http://, https://, or no protocol.

I had a go at modifying that Gruber Regex to do this, and came up with `^\b((?:https?:\/\/|(?!\w+:\/\/))(?:[^\s()<>]+|\(([^\s()<>]+|(\([^\s()<>]+\)))*\))+(?:\(([^\s()<>]+|(\([^\s()<>]+\)))*\)|[^\s`!()\[\]{};:'".,<>?«»“”‘’]))$`
which may have subtle bugs but seems to do the trick.

**Comment by ridem** [comment]
I haven't looked at it into detail, but I can't make this regex work on regex101. I get an "infinite loop" and a warning for "terrible backtracking". Any thoughts on it?

Maybe for this particular issue (tracking links) we want to keep it simple, and just exclude tags that start with "mailto" as an href:
`(<a.*?href\s*?=\s*?['"])((?!mailto).*)(['"].*?>)([\s\S]*?)(<\/a>)`

**Comment by emorikawa** [comment]
@ridem, Thank you for looking into this! I just rebased your patch onto master and pushed.

I agree that ignoring `mailto` links like this is definitely a safer way to go for now. Longer term, however, I think we should use js to properly parse the urls and check for a whitelist of protocols. For the time being this will fix the immediate problem. Thank you!

**Pull request closed without merging**
