### PR TITLE
Add mail rule action to mark unimportant

### LINKED ISSUE #3162: Mail rule action: mark as not important
macOS 10.12.2; N1 0.4.402

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
 Gmail web UI.

--

The list of actions for a Gmail mail rule presently includes "mark as important", but not "mark as unimportant".

Since Gmail applies these automatically, this would be useful for teaching it what's important.

### PR DESCRIPTION
**Pull request by OJFord**
Marked WIP since I haven't tested it, I don't know if perhaps something else needs to happen for the UI to work? Will check soon.

Closes #3162.

### CODE REVIEW

**Comment by OJFord** [comment]
I still can't get a build working to test it, it's complaining that those no file `src/request/...`, which is true, so 🤷‍♂️.

**Comment by grinich** [comment]
Hey Ollie-- thanks for the PR. This sounds like a great feature to add but we can't merge and break master with a WIP section. If you're looking for other folks to help out, I recommend asking in the [community Slack channel](http://slack-invite.nylas.com/). For now I'm going to have to close this PR but please re-open when it's ready to get merged! 👍

**Comment by OJFord** [comment]
@grinich Sure, wasn't expecting a merge without checking how it renders!

My trial will expire in a few days though, and I gather I won't have access to Mail Rules at all in the free version, so I'll leave this for someone else (with Pro) to pick it up if they want to, or I will if MRs are ever in the freeloader edition 🙂 .

**Comment by OJFord** [comment]
Oh, actually, FWIW this is the one I'm fairly confident works (i.e. an interested third-party should check, but...) - I was confused with my other PR (which I'll close for the same reason as this one) #3164 which actually adds a new button, so I was concerned that the placement of it might look weird, etc.

**Comment by grinich** [comment]
Do you have a screenshot?

**Comment by OJFord** [comment]
Nope, I haven't been able to build, so I can only guess/infer based on my essentially zero knowledge of React...

**Pull request closed without merging**
