### PR TITLE
Rename some variables from atom to nylas

### PR DESCRIPTION
**Pull request by mbilker**
The commits in relation to this pull request change the variable names from `atom` to `nylas` in the build scripts. I do not know if they should be `nylas` or `n1`.

Only commit 3a5e0f0 renames `atom.coffee` to `nylas.coffee`. I found the referenced files associated with the renamed file and altered them to point to the new file.

The name for a563f1d is not what the title says. I changed `engines?.atom?` to `engines?.nylas?`. That commit reverts that. Also, there were many other locations I would need to change and test if regressions occur.

### CODE REVIEW

**Comment by bengotow** [comment]
Thanks for submitting this PR! This is something we've been meaning to clean up for a while. I'll review these changes this week and make sure the CI builds still run properly on mac/win/linux before we land it. Stay tuned.

**Comment by mbilker** [comment]
@bengotow Thank you very much! I haven't fully tested the build process on Windows (as I don't use Windows on a regular basis), but I do use N1 on my Mac and Linux machines.

**Comment by mbilker** [comment]
The CI is still not working on 0.12 which is strange.

**Comment by mbilker** [comment]
#51602f69a54ee11b72e624ba7e63503f329a75d1 implements the changes in this PR, but better.

**Pull request closed without merging**
