### PR TITLE
Added Markdown plugin

### PR DESCRIPTION
**Pull request by orschiro**

### CODE REVIEW

**Comment by jackiehluo** [comment]
@orschiro Thanks for the PR! Looks like a really cool plugin. Could you move the listing into the Community Plugins section so people know that it doesn't ship with N1?

**Comment by orschiro** [comment]
Dear @jackiehluo,

Done. Thank you for your friendly help!

Warmly,

~Robert

**Comment by jackiehluo** [comment]
@orschiro Oh, one more question. Could you sign the CLA? Unfortunately, I can't merge in the changes without it. Thanks so much!

**Comment by orschiro** [comment]
Dear Jackie,

  

I am not sure about this one since I am not the original developer of the
plugin.

  

I just wanted to make sure that this plugin is receiving attention, thus
adding it to the list.

  

How should we proceed?

  

Thankfully,

  

~Robert

  
Sent from [Nylas N1](https://nylas.com/n1?ref=n1), the extensible, open source
mail client.  

On Apr 15 2016, at 7:04 am, Jackie Luo &lt;notifications@github.com&gt; wrote:  

> [@orschiro](https://github.com/orschiro) Oh, one more question. Could you
sign the CLA? Unfortunately, I can't merge in the changes without it. Thanks
so much!

>

> —  
You are receiving this because you were mentioned.  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/pull/1961#issuecomment-210288543)

**Comment by grinich** [comment]
@orschiro who is the original developer?

**Comment by orschiro** [comment]
Dear @grinich,

According to the [repo](https://github.com/evenh/n1-markdown) it's [evenh](https://github.com/evenh).

Warmly,

~Robert

**Comment by Trozz** [comment]
as this plugin isn't part of N1 would they need to sign the CLA? as this is simply updating the readme?

**Comment by mbilker** [comment]
Also, that plugin would need to be updated for N1's newer API changes.

**Comment by bengotow** [comment]
Hey folks! Anyone want to work on updating this plugin a bit? Otherwise we want to go ahead and close this and re-open if the plugin is updated.

**Pull request closed without merging**
