### PR TITLE
Added cmd+a / ctrl+a for Outlook template threadlist selection

### PR DESCRIPTION
**Pull request by cmbankester**
This functionality is consistent with Outlook's web app and mac/windows apps

### CODE REVIEW

**Comment by bengotow** [comment]
Hey @cmbankester — thanks for filing this. We've been holding off adding support for Cmd-A because it currently has some strange side-effects due to the way keyboard shortcuts are implemented. (It makes it so that pressing Cmd-A in the search field selects threads instead of selecting the search text.) We should be able to get this fixed in the next month or so, though.

**Comment by cmbankester** [comment]
@bengotow Alright, sounds good. I've been using it locally for a while and I haven't noticed anything weird. Care to elaborate?

Also, should I close this PR out?

**Comment by emorikawa** [comment]
@cmbankester, yeah, unfortunately `cmd+a` is a very overloaded keyboard command that fights with native browser behavior, the Menu system, and the extensible keymaps which you added to. We're currently working on a major refactor to better decouple the tightly bound menu shortcuts with commands like this one.

Thank you so much, however, for taking the time to track this down and submit a pull request! I'm going to close this issue since the Outlook.cson file will likely change in the refactor. Also, since the pull request our account-store underwent a separate major refactor that made the indentation problem you found obsolete.

Thanks

**Comment by cmbankester** [comment]
Excellent. No problem, @emorikawa.

**Pull request closed without merging**
